### ISSUE TITLE
Cross language testing for v1

### ISSUE THREAD

**Issue by truncs** [uber/tchannel-java#40]
We should atleast try doing some test around using python client with tchannel-java server and vice versa and possible for a couple of encoding schemes.

**Comment by willsalz** [comment]
Tested Against the tchannel-python/examples/simple/json/client.py. I'll do some Go and Node.js JSON testing followed by Thrift.

Another possibility for xlang testing, instead of trying to run other language's examples, would be to write our own examples in other languages and keep them in the tchannel-java repo. This isn't ideal, but until there is a unified set of examples we can follow we'l all have to modify each others examples to make them play nicely.

**Comment by willsalz** [comment]
Basic node.js compatibility seems fine against the thrift KeyValue example:

```lang=bash
$ tcurl -p localhost:8888 keyvalue-service KeyValue::setValue  -t keyvalue.thrift -3 '{"key":"foo", "value": "bar"}'
> "Got call response ok"
> undefined
```

```lang=bash
$ tcurl -p localhost:8888 keyvalue-service KeyValue::getValue  -t keyvalue.thrift -3 '{"key":"foo"}'
> "Got call response ok"
> "bar"
```

**Comment by truncs** [comment]
Nice !
Should we add a small doc on how to do this ? Or maybe it should live under the tchannel repo

**Comment by willsalz** [comment]
Yeah I'm struggling with the best way. I've got a diff that includes examples from go and Python ( and I can add node ). Instead of running them manually I'm going to add a test to channel-core that shells out and runs the clients against a Java server and vice-versa to automate running these. 

📧 | wjs@uber
🚙 | Logistics and Mapping
📱 | 908.304.8493

/* sent from my mobile */
