### ISSUE TITLE
Application headers shouldn't always be a map

### ISSUE THREAD

**Issue by ShanniLi** [uber/tchannel-java#84]
as raw: string
as thrift: string
as json: JSON

Otherwise, it will have problem talking to other languages.

cc: @willsalz @truncs

**Comment by willsalz** [comment]
@ShanniLi a little more description in bugs would be useful; I'm not sure why the Java implementation of the Application headers would be an issue with cross-language compatibility, other than if it introduced an API inconsistency, but AFAIK other languages use similar key-value data structures for representing their Application Headers in code.

**Comment by ShanniLi** [comment]
@willsalz 
It is a JSON object for as-json:
https://github.com/uber/tchannel-node/blob/master/as/json.js#L115

It is string for as-thrift
https://github.com/uber/tchannel-node/blob/master/as/thrift.js#L269

**Comment by willsalz** [comment]
Two things:
- The API that we expose to clients for application headers e.g.g Map, MultiMap, etc. is completely unrelated to how the objects are serialized. So I'm still unsure what this issue is referencing.
- JSON-as-TChannel is *not* a JSON object, but rather encoded the same was as Thrift. The Docs are incorrect here. Please see: https://github.com/uber/tchannel/pull/1206 and https://github.com/uber/tchannel-python/pull/187. I'll put up a PR to fix the docs.

**Comment by ShanniLi** [comment]
Oh, I missed the PR for other languages. tchannel-node doesn't have that key-value format, i.e., as-json in node supports all JSON objects in head.

I just asked offline. Not sure we have a consensus on this matter yet ...

**Comment by ShanniLi** [comment]
it seems it is tchannel-node that is different from other languages. Well, one less thing to track. :)
